name: Make release assets

on:
  release:
    types:
      - created

jobs:
  make-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - run: tar czf starter.tgz *.nix

      - name: Upload assets
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./starter.tgz
          overwrite: true
